/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sharad' at '2/1/17 4:12 PM' with Gradle 2.14.1
 *
 * @author sharad, @date 2/1/17 4:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
